# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='名字', max_length=32),
        ),
    ]
