# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_userinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renshu', models.CharField(max_length=3, null=True)),
                ('chepai', models.CharField(max_length=8, null=True)),
                ('xinghao', models.CharField(max_length=32, null=True)),
                ('chejia', models.CharField(max_length=32, null=True)),
                ('tupian', models.CharField(max_length=77, null=True)),
                ('beizhu', models.TextField(max_length=512, null=True)),
                ('fuwu', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '管理用户'), (3, '司机')], default=1),
        ),
    ]
