# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20180911_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_OM_DepartmentInfo_UserInfo_rn', related_query_name='f_OM_DepartmentInfo_UserInfo_rqn', to='car.DepartmentInfo'),
        ),
    ]
