# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_userinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='department',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
