# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-14 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20180911_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.DeleteModel(
            name='DepartmentInfo',
        ),
    ]
