# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-14 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20180914_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='PicHash',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
