# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-14 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_carinfo_pichash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='tupian',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
