# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-14 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20180914_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='chepai',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='renshu',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
