# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-18 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20180914_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.CharField(db_index=True, default=0, max_length=1)),
                ('using_time_start', models.DateTimeField(db_index=True)),
                ('using_time_stop', models.DateTimeField(db_index=True)),
                ('chufadi', models.CharField(max_length=77, null=True)),
                ('mudidi', models.CharField(max_length=77, null=True)),
                ('carinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_OM_carinfo_usecar_rn', related_query_name='f_OM_carinfo_usecar_rqn', to='car.CarInfo')),
                ('shenqingren_userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shenqingren_f_OM_userinfo_usecar_rn', related_query_name='shenqingren_f_OM_userinfo_usecar_rqn', to=settings.AUTH_USER_MODEL)),
                ('siji_userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siji_f_OM_userinfo_usecar_rn', related_query_name='siji_f_OM_userinfo_usecar_rqn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
