# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20180919_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecar',
            name='NormalUserTip',
            field=models.CharField(db_index=True, default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='usecar',
            name='RefuseReason',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='usecar',
            name='status_code',
            field=models.CharField(db_index=True, default='2', max_length=1),
        ),
    ]
