# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20180925_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecar',
            name='NormalUserTip',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
