# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_auto_20180925_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecar',
            name='afterdistance',
            field=models.CharField(max_length=77, null=True),
        ),
        migrations.AddField(
            model_name='usecar',
            name='beforedistance',
            field=models.CharField(max_length=77, null=True),
        ),
    ]
