# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_auto_20180927_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='receive_email',
            field=models.CharField(default='xxx@xx.com', max_length=47),
        ),
    ]
